### PR TITLE
Rename top-level menu to Batches

### PR DESCRIPTION
**Pull request by jjeaton**
Locomotive is fairly meaningless in the admin, this should
help users find the menu more easily.

Renamed the admin page title to 'Batch Processes' and made the strings
translatable.

Would love some other thoughts here :sparkles:

### CODE REVIEW

**Comment by norcross** [comment]
does this include a menu icon as well?

**Comment by jjeaton** [comment]
@norcross It doesn't, that could be a separate PR.

**Comment by norcross** [comment]
sounds good. i'll do some digging there.

**Comment by jjeaton** [comment]
This also makes me think whether we really need a top level menu item, or if we should move this into the Tools menu... We wouldn't need a menu icon then, and also are not adding to the glut of top level items. The only real reason to have a top level menu is :sparkles: Marketing! ☄️ ✨  or if you need submenu items. I'm not sure we'd ever need submenu items here.

**Comment by JasonHoffmann** [comment]
I can't imagine a day when this is more then just one screen. In which case you really don't need it's own menu item. Do we think the  ✨ Marketing! :comet: ✨ value is worth it? For developers installing it on clients sites, they would probably want it tucked away a bit right?

**Comment by jjeaton** [comment]
I'd be OK with moving it to Tools menu.

**Comment by jjeaton** [comment]
It's agreed then, we're moving this to the Tools menu. I can come back to this, but if anyone wants to take it in the meantime, feel free.

**Comment by JasonHoffmann** [comment]
Sure, same PR or different one?

**Comment by jjeaton** [comment]
same is fine since this was a course correction

**Comment by JasonHoffmann** [comment]
Cool, I'll add it.

**Comment by jjeaton** [comment]
@JasonHoffmann tests are failing.  We need this fix applied to our repo as well: https://github.com/reaktivstudios/civil-comments/pull/5

**Comment by JasonHoffmann** [comment]
I'll dig in.

**Comment by JasonHoffmann** [comment]
Tests have been fixed

**Pull request merged**
